#!/bin/bash

echo
echo "Downloading the latest elfin-library from Github."
echo

ADDON_DIR='elfin'
RAW_URL='https://raw.githubusercontent.com/joy13975/elfin-library/master'

files=(xdb.json library.blend)
for file in "${files[@]}"
do
	bz2_file=${file}.tar.bz2
	curl "$RAW_URL/$bz2_file" > "$bz2_file"
	tar xjf "$bz2_file" -C "$ADDON_DIR"
	rm -f "$bz2_file"
done

echo
echo "Done fetching."
echo